/*
 * File: ActionCurrentCalls.js
 * Date: Wed Jan 11 2012 19:16:56 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ActionCurrentCalls = Ext.extend(ActionCurrentCallsUi, {
    initComponent: function() {
        ActionCurrentCalls.superclass.initComponent.call(this);
    }
});
Ext.reg('ActionCurrentCalls', ActionCurrentCalls);