/*
 * File: ActionChooseUser.ui.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ActionChooseUserUi = Ext.extend(Ext.form.FieldSet, {
    title: 'Benutzer wählen',
    initComponent: function() {
        this.items = [
            {
                xtype: 'numberfield',
                fieldLabel: 'Durchwahl-Nr',
                anchor: '100%',
                ref: 'extensionNumber'
            },
            {
                xtype: 'checkbox',
                fieldLabel: 'Speichern',
                boxLabel: '',
                anchor: '100%',
                ref: 'saveExtension'
            },
            {
                xtype: 'button',
                text: 'Benutzer festlegen',
                ref: 'buttonChooseUser'
            }
        ];
        ActionChooseUserUi.superclass.initComponent.call(this);
    }
});
