/*
 * File: ActionStartCall.js
 * Date: Wed Jan 11 2012 13:48:09 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ActionStartCall = Ext.extend(ActionStartCallUi, {
    asteriskManager: null,
    userNumber: null,
    
    initComponent: function() {
        ActionStartCall.superclass.initComponent.call(this);
        
        this.buttonStartCall.on('click', this.startCall, this);
    },
    
    setAsteriskManager: function(asteriskManager){
        this.asteriskManager = asteriskManager;
    },
    
    startCall: function(){
        var to = this.remoteNumber.getValue();
        var outgoingCalllerId = this.localName.getValue();
        if(!outgoingCalllerId || outgoingCalllerId == "")
            outgoingCalllerId = "PhoneManager";
        this.asteriskManager.startCall(to, outgoingCalllerId);
    },
    
    updateUserNumber: function(nr){
        this.userNumber = nr;
    }
});
Ext.reg('ActionStartCall', ActionStartCall);