/*
 * File: ActionCurrentCalls.ui.js
 * Date: Sun Jan 15 2012 20:57:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ActionCurrentCallsUi = Ext.extend(Ext.form.FieldSet, {
    title: 'Aktive Anrufe',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                border: false,
                items: [
                    {
                        xtype: 'label',
                        text: 'Keine aktiven Anrufe',
                        ref: '../statusLabel'
                    }
                ]
            }
        ];
        ActionCurrentCallsUi.superclass.initComponent.call(this);
    }
});
