/*
 * File: ActionListUsers.js
 * Date: Wed Jan 11 2012 13:48:09 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ActionListUsers = Ext.extend(ActionListUsersUi, {

    initComponent: function() {
        ActionListUsers.superclass.initComponent.call(this);
        
        // Registriere Listener auf UI-Komponenten
        this.buttonReload.on('click', this.reload, this);
    },
    
    reload: function(){
        this.load();
    },
    
    load: function(){
        // TODO über asteriskmanager array mit daten holen
        var data = [
            ['10', 'Zentrale', '???'],
            ['23', 'Lukas', '???'],
            ['30', 'Christopher', '???'],
            ['50', 'Bernhard', '???']
        ];
        this.results.getStore().loadData(data);
    }
    
});
Ext.reg('ActionListUsers', ActionListUsers);