/*
 * File: CommanderAction.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CommanderAction = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        CommanderAction.superclass.constructor.call(this, Ext.apply({
            storeId: 'CommanderAction',
            data: [
                [
                    "hangup",
                    'Auflegen!'
                ]
            ],
            fields: [
                {
                    name: 'action'
                },
                {
                    name: 'description'
                }
            ]
        }, cfg));
    }
});
new CommanderAction();