/*
 * File: CommanderWindow.ui.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CommanderWindowUi = Ext.extend(Ext.Window, {
    title: 'Commander',
    width: 569,
    height: 617,
    layout: 'fit',
    draggable: false,
    modal: true,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                border: false,
                layout: 'border',
                padding: 10,
                items: [
                    {
                        xtype: 'form',
                        title: 'Eingabe',
                        region: 'north',
                        height: 234,
                        border: false,
                        padding: 10,
                        items: [
                            {
                                xtype: 'combo',
                                fieldLabel: 'Aktion',
                                anchor: '100%',
                                store: 'CommanderAction',
                                displayField: 'action',
                                mode: 'local',
                                valueField: 'action',
                                ref: '../../actionCombo'
                            },
                            {
                                xtype: 'displayfield',
                                value: 'Bitte Aktion wählen.',
                                fieldLabel: '',
                                anchor: '100%',
                                ref: '../../actionDescription'
                            },
                            {
                                xtype: 'editorgrid',
                                store: 'CommanderActionParam',
                                fieldLabel: 'Parameter',
                                height: 130,
                                clicksToEdit: 1,
                                ref: '../../paramsGrid',
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'property',
                                        header: 'Eigenschaft',
                                        sortable: true,
                                        width: 100,
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Wert',
                                        sortable: true,
                                        width: 130,
                                        dataIndex: 'defaultvalue',
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        header: 'Beschreibung',
                                        sortable: true,
                                        width: 170,
                                        dataIndex: 'description',
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    }
                                ],
                                tbar: {
                                    xtype: 'toolbar',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'Hinzufügen',
                                            ref: '../../../../buttonPropertyAdd'
                                        },
                                        {
                                            xtype: 'button',
                                            text: 'Löschen',
                                            ref: '../../../../buttonPropertyRemove'
                                        }
                                    ]
                                }
                            },
                            {
                                xtype: 'button',
                                text: 'Abfrage starten',
                                ref: '../../buttonExecute'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Ausgabe',
                        region: 'center',
                        border: false,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'panel',
                                border: false,
                                autoScroll: true,
                                ref: '../../resultArea'
                            }
                        ]
                    }
                ]
            }
        ];
        CommanderWindowUi.superclass.initComponent.call(this);
    }
});
