/*
 * File: CommanderActionParam.js
 * Date: Wed Jan 25 2012 18:55:22 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CommanderActionParam = Ext.extend(Ext.data.ArrayStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        CommanderActionParam.superclass.constructor.call(this, Ext.apply({
            storeId: 'CommanderActionParam',
            fields: [
                {
                    name: 'property'
                },
                {
                    name: 'defaultvalue'
                },
                {
                    name: 'description'
                }
            ]
        }, cfg));
    }
});
new CommanderActionParam();