/*
 * File: EventListenerWindow.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

EventListenerWindow = Ext.extend(EventListenerWindowUi, {
    
    asteriskManager: null,
    listening: false,
    eventCounter: 0,
    
    initComponent: function() {
        EventListenerWindow.superclass.initComponent.call(this);
        
        this.buttonToogleListener.on('click', this.toggleListener, this);
    },
    
    setAsteriskManager: function(asteriskManager){
        this.asteriskManager = asteriskManager;
    },    
    
    toggleListener: function(){
        this.listening = !this.listening;
        
        if(this.listening)
            this.startListening();
    },

    startListening: function(){
        // Starte Command!
        this.asteriskManager.executeCommand('waitevent', {}, this.printResult, this);        
    },
    
    printResult: function(results){
        this.eventCounter++;
        
        if(this.listening)
            this.startListening();        
        
        var htmlOutput = "";
        for(var itemKey in results){
            if(!results[itemKey] || itemKey == "remove")
                continue;
            
            var item = results[itemKey];
            var itemStr = itemKey + ": <br/>" +
                "<table width=\"100%\">";
            for(var propKey in item){
                var prop = item[propKey];
                itemStr += "<tr><td width=\"30%\"><b>"+propKey+":</b></td>"
                            + "<td width=\"70%\">" + prop + "</td></tr>";
            }
            itemStr += "</table>";
            htmlOutput += "<div style=\"margin: 5px; padding: 5px; border: solid 1px silver;\">" + itemStr + "</div>"
        }        
        
        var panel = new Ext.Panel({
            title: 'Ev'+this.eventCounter,
            autoscroll: true,
            layout: 'fit',
            html: htmlOutput
        });
        this.resultArea.add(panel);
    }
});
