/*
 * File: LoginWindow.ui.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

LoginWindowUi = Ext.extend(Ext.Window, {
    title: 'PhoneManager Login',
    width: 334,
    height: 144,
    layout: 'fit',
    closable: false,
    resizable: false,
    modal: true,
    draggable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                border: false,
                padding: 10,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Username',
                        anchor: '100%',
                        ref: '../username'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Secret',
                        anchor: '100%',
                        inputType: 'password',
                        ref: '../secret'
                    },
                    {
                        xtype: 'checkbox',
                        fieldLabel: 'Speichern',
                        boxLabel: '',
                        anchor: '100%',
                        ref: '../save'
                    },
                    {
                        xtype: 'button',
                        text: 'Anmelden',
                        ref: '../buttonLogin'
                    }
                ]
            }
        ];
        LoginWindowUi.superclass.initComponent.call(this);
    }
});
