/*
 * File: PhoneManager.js
 * Date: Wed Jan 11 2012 13:48:09 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

PhoneManager = Ext.extend(PhoneManagerUi, {
    asteriskManager: null,
    
    initComponent: function() {
        PhoneManager.superclass.initComponent.call(this);
        
        // Definiere neue Events
        this.addEvents('logout');
        
        // Registriere Listener auf UI-Elemente
        this.buttonLogout.on('click', this.logout, this);
        this.buttonCommander.on('click', this.startCommander, this);
        this.buttonEventListener.on('click', this.startEventListener, this);
        
        // Registriere Listener auf eigene Events
        this.actionChooseUser.on('userChanged', this.updateUser, this);
        
        // Lade einzelne Komponenten
        this.actionListUsers.load();
   },
    
    setAsteriskManager: function(asteriskManager){
        this.asteriskManager = asteriskManager;
        // Publiziere AsteriskManager
        this.actionStartCall.setAsteriskManager(asteriskManager);
    },
    
    updateUser: function(nr){
        this.asteriskManager.setUser(nr);
        this.statusLabel.setText('Benutzer auf ' + nr + ' gesetzt! Hallo ;-)');
        this.actionStartCall.updateUserNumber(nr);
    },
    
    logout: function(){
        this.fireEvent('logout');
    },
    
    startCommander: function(){
        var commander = new Commander();
        commander.setAsteriskManager(this.asteriskManager);
        commander.show();
    },
    
    startEventListener: function(){
        var eventListener = new EventListener();
        eventListener.setAsteriskManager(this.asteriskManager);
        eventListener.show();        
    }    
});
