/*
 * File: WaitingWindow.js
 * Date: Wed Jan 11 2012 18:55:57 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */
WaitingWindow = Ext.extend(WaitingWindowUi, {
    initComponent: function() {
        WaitingWindow.superclass.initComponent.call(this);
        
        this.on('show', function(){this.progressbar.wait();}, this);
        this.on('hide', function(){this.progressbar.reset();}, this);
    }
});