/*
 * File: xds_index.js
 * Date: Sat Feb 04 2012 17:54:13 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    Ext.QuickTips.init();
    var cmp1 = new PhoneManager({
        renderTo: Ext.getBody()
    });
    cmp1.show();
    var cmp2 = new LoginWindow({
        renderTo: Ext.getBody()
    });
    cmp2.show();
    var cmp3 = new CommanderWindow({
        renderTo: Ext.getBody()
    });
    cmp3.show();
    var cmp4 = new EventListenerWindow({
        renderTo: Ext.getBody()
    });
    cmp4.show();
    var cmp5 = new WaitingWindow({
        renderTo: Ext.getBody()
    });
    cmp5.show();
});
