/*
 * File: ActionChooseUser.js
 * Date: Wed Jan 11 2012 13:48:09 GMT+0100 (CET)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ActionChooseUser = Ext.extend(ActionChooseUserUi, {
    
    userNumber: null,
    
    initComponent: function() {
        ActionChooseUser.superclass.initComponent.call(this);
        
        // Definiere neue Events
        this.addEvents('userChanged');
        
        // Registriere Listener auf UI-Komponenten
        this.buttonChooseUser.on('click', this.chooseUser, this);        
        
        // Lade lokalen Benutzer aus Cookie
        this.loadUserNumber();
    },
    
    chooseUser: function(){
        var nr = this.extensionNumber.getValue();
        var save = this.saveExtension.getValue();

        this.setUserNumber(nr);
        if(save)
            Ext.util.Cookies.set('userNumber', nr);
        else
            Ext.util.Cookies.set('userNumber', '', new Date());
    },
    
    loadUserNumber: function(){
        var nr = Ext.util.Cookies.get('userNumber');
        if(nr != null){
            this.setUserNumber(nr);
            this.saveExtension.setValue(true);
        }
    },
    
    setUserNumber: function(nr){
        this.userNumber = nr;
        this.extensionNumber.setValue(nr);
        this.fireEvent('userChanged', nr);
    }
});
Ext.reg('ActionChooseUser', ActionChooseUser);